default: &default
    adapter: postgresql
    encoding: unicode
    host: db
    username: postgres
    password: 123123
    pool: 5

development:
    <<: *default
    database: app_development

test:
    <<: *default
    database: test
    username: postgres
    password: 123123

production:
    <<: *default
    database: app_production
    username: app
    password: <%= ENV["APP_DATABASE_PASSWORD"] %>
